import 'chess_models.dart';

const List<DifficultyConfig> DIFFICULTY_LEVELS = [
  DifficultyConfig(
    level: 1,
    name: 'Novice (600 Elo)',
    elo: 600,
    depth: 1,
    skillLevel: 1,
    blunderProbability: 0.35,
    moveTimeMs: 150,
    evalNoise: 320,
    bookMaxPlies: 1,
    temperature: 360.0,
    useQuiescence: false,
    nodeBudget: 400,
    description: 'Makes frequent casual mistakes, overlooks simple hanging pieces.',
    badgeColor: '0xFFD97706',
  ),
  DifficultyConfig(
    level: 2,
    name: 'Beginner (800 Elo)',
    elo: 800,
    depth: 2,
    skillLevel: 3,
    blunderProbability: 0.22,
    moveTimeMs: 200,
    evalNoise: 220,
    bookMaxPlies: 2,
    temperature: 240.0,
    useQuiescence: false,
    nodeBudget: 1200,
    description: 'Knows basic moves, but struggles with multi-move tactics and pins.',
    badgeColor: '0xFFCA8A04',
  ),
  DifficultyConfig(
    level: 3,
    name: 'Casual (1000 Elo)',
    elo: 1000,
    depth: 2,
    skillLevel: 5,
    blunderProbability: 0.12,
    moveTimeMs: 250,
    evalNoise: 140,
    bookMaxPlies: 4,
    temperature: 160.0,
    useQuiescence: false,
    nodeBudget: 3500,
    description: 'Solid opening awareness, occasionally blunders tactics in complex positions.',
    badgeColor: '0xFF059669',
  ),
  DifficultyConfig(
    level: 4,
    name: 'Club Novice (1200 Elo)',
    elo: 1200,
    depth: 3,
    skillLevel: 8,
    blunderProbability: 0.06,
    moveTimeMs: 350,
    evalNoise: 80,
    bookMaxPlies: 6,
    temperature: 90.0,
    useQuiescence: true,
    nodeBudget: 9000,
    description: 'Aggressive Queen attacker. Understands center control and tactical motifs.',
    badgeColor: '0xFF0D9488',
  ),
  DifficultyConfig(
    level: 5,
    name: 'Intermediate (1400 Elo)',
    elo: 1400,
    depth: 3,
    skillLevel: 11,
    blunderProbability: 0.02,
    moveTimeMs: 400,
    evalNoise: 45,
    bookMaxPlies: 7,
    temperature: 50.0,
    useQuiescence: true,
    nodeBudget: 16000,
    description: 'Rarely leaves pieces hanging. Formulates tactical attack plans.',
    badgeColor: '0xFF0284C7',
  ),
  DifficultyConfig(
    level: 6,
    name: 'Advanced (1600 Elo)',
    elo: 1600,
    depth: 3,
    skillLevel: 14,
    blunderProbability: 0.0,
    moveTimeMs: 500,
    evalNoise: 20,
    bookMaxPlies: 8,
    temperature: 30.0,
    useQuiescence: true,
    nodeBudget: 28000,
    description: 'Strong tactical vision, good pawn structure knowledge, active endgames.',
    badgeColor: '0xFF2563EB',
  ),
  DifficultyConfig(
    level: 7,
    name: 'Club Player (1800 Elo)',
    elo: 1800,
    depth: 4,
    skillLevel: 16,
    blunderProbability: 0.0,
    moveTimeMs: 600,
    evalNoise: 0,
    bookMaxPlies: 10,
    temperature: 15.0,
    useQuiescence: true,
    nodeBudget: 45000,
    description: 'Plays precise theoretical lines and punishes small positional errors.',
    badgeColor: '0xFF4F46E5',
  ),
  DifficultyConfig(
    level: 8,
    name: 'Expert (2000 Elo)',
    elo: 2000,
    depth: 4,
    skillLevel: 18,
    blunderProbability: 0.0,
    moveTimeMs: 700,
    evalNoise: 0,
    bookMaxPlies: 12,
    temperature: 6.0,
    useQuiescence: true,
    nodeBudget: 70000,
    description: 'Formidable opponent with deep calculation and strong endgame technique.',
    badgeColor: '0xFF9333EA',
  ),
  DifficultyConfig(
    level: 9,
    name: 'Master (2200 Elo)',
    elo: 2200,
    depth: 5,
    skillLevel: 19,
    blunderProbability: 0.0,
    moveTimeMs: 800,
    evalNoise: 0,
    bookMaxPlies: 14,
    temperature: 3.0,
    useQuiescence: true,
    nodeBudget: 95000,
    description: 'Near-flawless tactical accuracy and strategic mastery.',
    badgeColor: '0xFFE11D48',
  ),
  DifficultyConfig(
    level: 10,
    name: 'Grandmaster (2500 Elo)',
    elo: 2500,
    depth: 5,
    skillLevel: 20,
    blunderProbability: 0.0,
    moveTimeMs: 900,
    evalNoise: 0,
    bookMaxPlies: 18,
    temperature: 1.0,
    useQuiescence: true,
    nodeBudget: 130000,
    description: 'Master-level iterative deepening with quiescence tactical horizon search.',
    badgeColor: '0xFFDC2626',
  ),
];

const List<AIPersonality> AI_PERSONALITIES = [
  AIPersonality(
    id: AIPersonalityId.balanced,
    name: 'Harmonic Engine',
    avatar: '⚖️',
    tagline: 'Objective, calm, and balanced',
    description: 'Plays standard chess theory, balances tactical aggression with solid positional structure.',
    kingAttackWeight: 1.0,
    centerControlWeight: 1.0,
    tacticalWeight: 1.0,
  ),
  AIPersonality(
    id: AIPersonalityId.aggressive,
    name: 'The Valkyrie',
    avatar: '⚔️',
    tagline: 'Ruthless kingside attacker',
    description: 'Sacrifices pawns for initiative, launches relentless kingside storms, and avoids quiet piece trades.',
    kingAttackWeight: 1.8,
    centerControlWeight: 0.9,
    tacticalWeight: 1.5,
  ),
  AIPersonality(
    id: AIPersonalityId.positional,
    name: 'The Architect',
    avatar: '🏰',
    tagline: 'Master of outposts and structure',
    description: 'Patient, squeezes subtle weaknesses, locks pawn structures, and maneuvers for overwhelming endgame superiority.',
    kingAttackWeight: 0.7,
    centerControlWeight: 1.6,
    tacticalWeight: 0.8,
  ),
  AIPersonality(
    id: AIPersonalityId.tactical,
    name: 'The Magician',
    avatar: '✨',
    tagline: 'Trickster and combinationalist',
    description: 'Loves sharp complications, pins, forks, and deflection tactics. Constant tactical alertness.',
    kingAttackWeight: 1.3,
    centerControlWeight: 1.0,
    tacticalWeight: 1.9,
  ),
];

const List<TimeControlConfig> TIME_CONTROLS = [
  TimeControlConfig(id: 'bullet_1_0', label: '1+0 Bullet', category: 'bullet', baseMinutes: 1, incrementSeconds: 0),
  TimeControlConfig(id: 'blitz_3_2', label: '3+2 Blitz', category: 'blitz', baseMinutes: 3, incrementSeconds: 2),
  TimeControlConfig(id: 'blitz_5_0', label: '5+0 Blitz', category: 'blitz', baseMinutes: 5, incrementSeconds: 0),
  TimeControlConfig(id: 'rapid_10_5', label: '10+5 Rapid', category: 'rapid', baseMinutes: 10, incrementSeconds: 5),
  TimeControlConfig(id: 'classical_30_0', label: '30+0 Classical', category: 'classical', baseMinutes: 30, incrementSeconds: 0),
  TimeControlConfig(id: 'none', label: 'No Clock (Casual)', category: 'none', baseMinutes: 0, incrementSeconds: 0),
];

const Map<BoardThemeId, BoardThemeColors> BOARD_THEMES = {
  BoardThemeId.emerald: BoardThemeColors(
    id: BoardThemeId.emerald,
    name: 'Emerald Classic',
    lightSquare: 0xFFEAE6D5,
    darkSquare: 0xFF5D7C51,
    selectedSquare: 0xFF10B981,
    lastMoveSquare: 0xFF10B981,
    checkSquare: 0xFFEF4444,
  ),
  BoardThemeId.slate: BoardThemeColors(
    id: BoardThemeId.slate,
    name: 'Slate Modern',
    lightSquare: 0xFFECEEF0,
    darkSquare: 0xFF8CA1B3,
    selectedSquare: 0xFF60A5FA,
    lastMoveSquare: 0xFF93C5FD,
    checkSquare: 0xFFF87171,
  ),
  BoardThemeId.wood: BoardThemeColors(
    id: BoardThemeId.wood,
    name: 'Walnut Wood',
    lightSquare: 0xFFF0D9B5,
    darkSquare: 0xFFB58863,
    selectedSquare: 0xFFD4A373,
    lastMoveSquare: 0xFFE9D8A6,
    checkSquare: 0xFFEF4444,
  ),
  BoardThemeId.sapphire: BoardThemeColors(
    id: BoardThemeId.sapphire,
    name: 'Sapphire Neon',
    lightSquare: 0xFFDCE8F5,
    darkSquare: 0xFF4A75A0,
    selectedSquare: 0xFF38BDF8,
    lastMoveSquare: 0xFF7DD3FC,
    checkSquare: 0xFFFB7185,
  ),
  BoardThemeId.onyx: BoardThemeColors(
    id: BoardThemeId.onyx,
    name: 'Carbon Dark',
    lightSquare: 0xFF71717A,
    darkSquare: 0xFF3F3F46,
    selectedSquare: 0xFFA1A1AA,
    lastMoveSquare: 0xFFD4D4D8,
    checkSquare: 0xFFDC2626,
  ),
};
