import 'chess_models.dart';

const List<DifficultyConfig> DIFFICULTY_LEVELS = [
  DifficultyConfig(
    level: 1,
    name: 'Novice (600 Elo)',
    elo: 600,
    depth: 2,
    skillLevel: 1,
    blunderProbability: 0.18,
    moveTimeMs: 500,
    evalNoise: 50,
    bookMaxPlies: 1,
    temperature: 35.0,
    useQuiescence: true,
    nodeBudget: 2000,
    description: 'Makes occasional positional mistakes but never drops pieces for free.',
    badgeColor: '0xFFD97706',
  ),
  DifficultyConfig(
    level: 2,
    name: 'Beginner (800 Elo)',
    elo: 800,
    depth: 3,
    skillLevel: 3,
    blunderProbability: 0.12,
    moveTimeMs: 600,
    evalNoise: 40,
    bookMaxPlies: 2,
    temperature: 28.0,
    useQuiescence: true,
    nodeBudget: 4000,
    description: 'Knows basic moves, occasionally misses multi-move tactics.',
    badgeColor: '0xFFCA8A04',
  ),
  DifficultyConfig(
    level: 3,
    name: 'Casual (1000 Elo)',
    elo: 1000,
    depth: 3,
    skillLevel: 5,
    blunderProbability: 0.06,
    moveTimeMs: 700,
    evalNoise: 30,
    bookMaxPlies: 4,
    temperature: 20.0,
    useQuiescence: true,
    nodeBudget: 8000,
    description: 'Solid opening awareness, occasionally misplays complex tactical positions.',
    badgeColor: '0xFF059669',
  ),
  DifficultyConfig(
    level: 4,
    name: 'Club Novice (1200 Elo)',
    elo: 1200,
    depth: 4,
    skillLevel: 8,
    blunderProbability: 0.03,
    moveTimeMs: 900,
    evalNoise: 18,
    bookMaxPlies: 6,
    temperature: 12.0,
    useQuiescence: true,
    nodeBudget: 15000,
    description: 'Aggressive Queen attacker. Understands center control and tactical motifs.',
    badgeColor: '0xFF0D9488',
  ),
  DifficultyConfig(
    level: 5,
    name: 'Intermediate (1400 Elo)',
    elo: 1400,
    depth: 4,
    skillLevel: 11,
    blunderProbability: 0.01,
    moveTimeMs: 1200,
    evalNoise: 10,
    bookMaxPlies: 7,
    temperature: 6.0,
    useQuiescence: true,
    nodeBudget: 25000,
    description: 'Never leaves pieces hanging. Formulates tactical attack plans.',
    badgeColor: '0xFF0284C7',
  ),
  DifficultyConfig(
    level: 6,
    name: 'Advanced (1600 Elo)',
    elo: 1600,
    depth: 5,
    skillLevel: 14,
    blunderProbability: 0.0,
    moveTimeMs: 1800,
    evalNoise: 5,
    bookMaxPlies: 8,
    temperature: 3.0,
    useQuiescence: true,
    nodeBudget: 50000,
    description: 'Strong tactical vision, good pawn structure knowledge, active endgames.',
    badgeColor: '0xFF2563EB',
  ),
  DifficultyConfig(
    level: 7,
    name: 'Club Player (1800 Elo)',
    elo: 1800,
    depth: 5,
    skillLevel: 16,
    blunderProbability: 0.0,
    moveTimeMs: 3000,
    evalNoise: 0,
    bookMaxPlies: 10,
    temperature: 1.5,
    useQuiescence: true,
    nodeBudget: 80000,
    description: 'Plays precise theoretical lines and punishes small positional errors.',
    badgeColor: '0xFF4F46E5',
  ),
  DifficultyConfig(
    level: 8,
    name: 'Expert (2000 Elo)',
    elo: 2000,
    depth: 6,
    skillLevel: 18,
    blunderProbability: 0.0,
    moveTimeMs: 5000,
    evalNoise: 0,
    bookMaxPlies: 12,
    temperature: 0.0,
    useQuiescence: true,
    nodeBudget: 150000,
    description: 'Formidable opponent with deep calculation and strong endgame technique.',
    badgeColor: '0xFF9333EA',
  ),
  DifficultyConfig(
    level: 9,
    name: 'Master (2200 Elo)',
    elo: 2200,
    depth: 7,
    skillLevel: 19,
    blunderProbability: 0.0,
    moveTimeMs: 8000,
    evalNoise: 0,
    bookMaxPlies: 16,
    temperature: 0.0,
    useQuiescence: true,
    nodeBudget: 400000,
    description: 'Near-flawless tactical accuracy and strategic mastery.',
    badgeColor: '0xFFE11D48',
  ),
  DifficultyConfig(
    level: 10,
    name: 'Grandmaster (2500 Elo)',
    elo: 2500,
    depth: 8,
    skillLevel: 20,
    blunderProbability: 0.0,
    moveTimeMs: 15000,
    evalNoise: 0,
    bookMaxPlies: 24,
    temperature: 0.0,
    useQuiescence: true,
    nodeBudget: 2000000,
    description: 'World-champion deep iterative minimax search with quiescence horizon calculation, persistent transposition cache, and 24-ply master repertoires.',
    badgeColor: '0xFFDC2626',
  ),
];

const List<AIPersonality> AI_PERSONALITIES = [
  AIPersonality(
    id: AIPersonalityId.balanced,
    name: 'Harmonic Engine',
    avatar: '⚖️',
    tagline: 'Objective, calm, and balanced',
    description: 'Plays standard chess theory, balances tactical aggression with solid positional structure.',
    kingAttackWeight: 1.0,
    centerControlWeight: 1.0,
    tacticalWeight: 1.0,
  ),
  AIPersonality(
    id: AIPersonalityId.aggressive,
    name: 'The Valkyrie',
    avatar: '⚔️',
    tagline: 'Ruthless kingside attacker',
    description: 'Sacrifices pawns for initiative, launches relentless kingside storms, and avoids quiet piece trades.',
    kingAttackWeight: 1.8,
    centerControlWeight: 0.9,
    tacticalWeight: 1.5,
  ),
  AIPersonality(
    id: AIPersonalityId.positional,
    name: 'The Architect',
    avatar: '🏰',
    tagline: 'Master of outposts and structure',
    description: 'Patient, squeezes subtle weaknesses, locks pawn structures, and maneuvers for overwhelming endgame superiority.',
    kingAttackWeight: 0.7,
    centerControlWeight: 1.6,
    tacticalWeight: 0.8,
  ),
  AIPersonality(
    id: AIPersonalityId.tactical,
    name: 'The Magician',
    avatar: '✨',
    tagline: 'Trickster and combinationalist',
    description: 'Loves sharp complications, pins, forks, and deflection tactics. Constant tactical alertness.',
    kingAttackWeight: 1.3,
    centerControlWeight: 1.0,
    tacticalWeight: 1.9,
  ),
];

const List<TimeControlConfig> TIME_CONTROLS = [
  TimeControlConfig(id: 'bullet_1_0', label: '1+0 Bullet', category: 'bullet', baseMinutes: 1, incrementSeconds: 0),
  TimeControlConfig(id: 'blitz_3_2', label: '3+2 Blitz', category: 'blitz', baseMinutes: 3, incrementSeconds: 2),
  TimeControlConfig(id: 'blitz_5_0', label: '5+0 Blitz', category: 'blitz', baseMinutes: 5, incrementSeconds: 0),
  TimeControlConfig(id: 'rapid_10_5', label: '10+5 Rapid', category: 'rapid', baseMinutes: 10, incrementSeconds: 5),
  TimeControlConfig(id: 'classical_30_0', label: '30+0 Classical', category: 'classical', baseMinutes: 30, incrementSeconds: 0),
  TimeControlConfig(id: 'none', label: 'No Clock (Casual)', category: 'none', baseMinutes: 0, incrementSeconds: 0),
];

const Map<BoardThemeId, BoardThemeColors> BOARD_THEMES = {
  BoardThemeId.emerald: BoardThemeColors(
    id: BoardThemeId.emerald,
    name: 'Emerald Classic',
    lightSquare: 0xFFEAE6D5,
    darkSquare: 0xFF5D7C51,
    selectedSquare: 0xFF10B981,
    lastMoveSquare: 0xFF10B981,
    checkSquare: 0xFFEF4444,
  ),
  BoardThemeId.slate: BoardThemeColors(
    id: BoardThemeId.slate,
    name: 'Slate Modern',
    lightSquare: 0xFFECEEF0,
    darkSquare: 0xFF8CA1B3,
    selectedSquare: 0xFF60A5FA,
    lastMoveSquare: 0xFF93C5FD,
    checkSquare: 0xFFF87171,
  ),
  BoardThemeId.wood: BoardThemeColors(
    id: BoardThemeId.wood,
    name: 'Walnut Wood',
    lightSquare: 0xFFF0D9B5,
    darkSquare: 0xFFB58863,
    selectedSquare: 0xFFD4A373,
    lastMoveSquare: 0xFFE9D8A6,
    checkSquare: 0xFFEF4444,
  ),
  BoardThemeId.sapphire: BoardThemeColors(
    id: BoardThemeId.sapphire,
    name: 'Sapphire Neon',
    lightSquare: 0xFFDCE8F5,
    darkSquare: 0xFF4A75A0,
    selectedSquare: 0xFF38BDF8,
    lastMoveSquare: 0xFF7DD3FC,
    checkSquare: 0xFFFB7185,
  ),
  BoardThemeId.onyx: BoardThemeColors(
    id: BoardThemeId.onyx,
    name: 'Carbon Dark',
    lightSquare: 0xFF71717A,
    darkSquare: 0xFF3F3F46,
    selectedSquare: 0xFFA1A1AA,
    lastMoveSquare: 0xFFD4D4D8,
    checkSquare: 0xFFDC2626,
  ),
};

class BotCharacter {
  final int level;
  final String name;
  final String title;
  final int elo;
  final String avatar;
  final AIPersonalityId personality;
  final String style;
  final String tier;
  final String desc;

  const BotCharacter({
    required this.level,
    required this.name,
    required this.title,
    required this.elo,
    required this.avatar,
    required this.personality,
    required this.style,
    required this.tier,
    required this.desc,
  });

  Map<String, dynamic> toMap() => {
    'level': level,
    'name': name,
    'title': title,
    'elo': elo,
    'avatar': avatar,
    'personality': personality,
    'style': style,
    'tier': tier,
    'desc': desc,
  };
}

const List<BotCharacter> BOT_CHARACTERS = [
  BotCharacter(
    level: 1,
    name: 'Jimmy',
    title: 'Novice Bot',
    elo: 600,
    avatar: '🤖',
    personality: AIPersonalityId.balanced,
    style: 'Casual',
    tier: 'beginner',
    desc: 'Overlooks hanging pieces, perfect for beginners learning basics.',
  ),
  BotCharacter(
    level: 2,
    name: 'Martin',
    title: 'Calm Novice',
    elo: 800,
    avatar: '🥋',
    personality: AIPersonalityId.balanced,
    style: 'Beginner',
    tier: 'beginner',
    desc: 'Knows rules and simple checks, struggles with multi-step tactics.',
  ),
  BotCharacter(
    level: 3,
    name: 'Elena',
    title: 'Sharp Casual',
    elo: 1000,
    avatar: '🎯',
    personality: AIPersonalityId.tactical,
    style: 'Tactical',
    tier: 'beginner',
    desc: 'Likes early attacks and pins, occasional tactical slips in endgames.',
  ),
  BotCharacter(
    level: 4,
    name: 'Nelson',
    title: 'Club Novice',
    elo: 1200,
    avatar: '⚔️',
    personality: AIPersonalityId.aggressive,
    style: 'Aggressive',
    tier: 'intermediate',
    desc: 'Aggressive queen attacker. Punishes passive openings quickly.',
  ),
  BotCharacter(
    level: 5,
    name: 'Antonio',
    title: 'Harmonic Intermediate',
    elo: 1400,
    avatar: '⚖️',
    personality: AIPersonalityId.balanced,
    style: 'Balanced',
    tier: 'intermediate',
    desc: 'Solid central control, patient development, balanced play.',
  ),
  BotCharacter(
    level: 6,
    name: 'Sofia',
    title: 'The Architect',
    elo: 1600,
    avatar: '🏰',
    personality: AIPersonalityId.positional,
    style: 'Positional',
    tier: 'intermediate',
    desc: 'Locks pawn structures, targets outpost squares, strategic mastery.',
  ),
  BotCharacter(
    level: 7,
    name: 'Laura',
    title: 'Tactical Magician',
    elo: 1800,
    avatar: '✨',
    personality: AIPersonalityId.tactical,
    style: 'Tricky',
    tier: 'master',
    desc: 'Constantly sets tactical traps, forks, and deflection tactics.',
  ),
  BotCharacter(
    level: 8,
    name: 'Viktor',
    title: 'Club Master',
    elo: 2000,
    avatar: '🦁',
    personality: AIPersonalityId.aggressive,
    style: 'Grandmaster',
    tier: 'master',
    desc: 'Fierce calculation and strong endgame conversion.',
  ),
  BotCharacter(
    level: 9,
    name: 'Alexander',
    title: 'International Master',
    elo: 2200,
    avatar: '🦅',
    personality: AIPersonalityId.positional,
    style: 'Master',
    tier: 'master',
    desc: 'Deep positional pressure, tight endgame play, and strategic mastery.',
  ),
  BotCharacter(
    level: 10,
    name: 'Magnus',
    title: 'World Champion',
    elo: 2500,
    avatar: '👑',
    personality: AIPersonalityId.balanced,
    style: 'World Champion',
    tier: 'master',
    desc: 'World-champion deep iterative minimax search with quiescence horizon calculation.',
  ),
];

BotCharacter getBotCharacter(int level) {
  return BOT_CHARACTERS.firstWhere(
    (b) => b.level == level,
    orElse: () => BOT_CHARACTERS[3], // Nelson (1200) fallback
  );
}

