import { DifficultyConfig, AIPersonality, AIPersonalityId, TimeControlConfig } from '../types/chess';

export const DIFFICULTY_LEVELS: DifficultyConfig[] = [
  {
    level: 1,
    name: 'Novice (600 Elo)',
    elo: 600,
    depth: 2,
    skillLevel: 1,
    blunderProbability: 0.18,
    moveTimeMs: 500,
    description: 'Makes frequent casual mistakes, overlooks simple hanging pieces.',
    avatarBg: 'from-amber-600 to-amber-800',
  },
  {
    level: 2,
    name: 'Beginner (800 Elo)',
    elo: 800,
    depth: 3,
    skillLevel: 3,
    blunderProbability: 0.12,
    moveTimeMs: 600,
    description: 'Knows basic moves, but struggles with multi-move tactics and pins.',
    avatarBg: 'from-yellow-600 to-amber-700',
  },
  {
    level: 3,
    name: 'Casual (1000 Elo)',
    elo: 1000,
    depth: 3,
    skillLevel: 5,
    blunderProbability: 0.06,
    moveTimeMs: 700,
    description: 'Solid opening awareness, occasionally blunders tactics in complex positions.',
    avatarBg: 'from-emerald-600 to-green-800',
  },
  {
    level: 4,
    name: 'Club Novice (1200 Elo)',
    elo: 1200,
    depth: 4,
    skillLevel: 8,
    blunderProbability: 0.03,
    moveTimeMs: 900,
    description: 'Understands basic strategy, center control, and common tactical motifs.',
    avatarBg: 'from-teal-600 to-emerald-800',
  },
  {
    level: 5,
    name: 'Intermediate (1400 Elo)',
    elo: 1400,
    depth: 4,
    skillLevel: 11,
    blunderProbability: 0.01,
    moveTimeMs: 1200,
    description: 'Rarely leaves pieces hanging. Formulates tactical attack plans.',
    avatarBg: 'from-cyan-600 to-blue-800',
  },
  {
    level: 6,
    name: 'Advanced (1600 Elo)',
    elo: 1600,
    depth: 5,
    skillLevel: 14,
    blunderProbability: 0.0,
    moveTimeMs: 1800,
    description: 'Strong tactical vision, good pawn structure knowledge, active endgames.',
    avatarBg: 'from-blue-600 to-indigo-800',
  },
  {
    level: 7,
    name: 'Club Player (1800 Elo)',
    elo: 1800,
    depth: 5,
    skillLevel: 16,
    blunderProbability: 0.0,
    moveTimeMs: 3000,
    description: 'Plays precise theoretical lines and punishes small positional errors.',
    avatarBg: 'from-indigo-600 to-purple-800',
  },
  {
    level: 8,
    name: 'Expert (2000 Elo)',
    elo: 2000,
    depth: 6,
    skillLevel: 18,
    blunderProbability: 0.0,
    moveTimeMs: 5000,
    description: 'Formidable opponent with deep calculation and strong endgame technique.',
    avatarBg: 'from-purple-600 to-fuchsia-800',
  },
  {
    level: 9,
    name: 'Master (2200 Elo)',
    elo: 2200,
    depth: 7,
    skillLevel: 19,
    blunderProbability: 0.0,
    moveTimeMs: 8000,
    description: 'Near-flawless tactical accuracy and strategic mastery.',
    avatarBg: 'from-rose-600 to-pink-900',
  },
  {
    level: 10,
    name: 'Grandmaster (2500 Elo)',
    elo: 2500,
    depth: 8,
    skillLevel: 20,
    blunderProbability: 0.0,
    moveTimeMs: 15000,
    description: 'Master-level iterative deepening with quiescence tactical horizon search.',
    avatarBg: 'from-red-600 to-amber-900',
  },
];

export const AI_PERSONALITIES: AIPersonality[] = [
  {
    id: 'balanced',
    name: 'Harmonic Engine',
    avatar: '⚖️',
    tagline: 'Objective, calm, and balanced',
    description: 'Plays standard chess theory, balances tactical aggression with solid positional structure.',
    kingAttackWeight: 1.0,
    centerControlWeight: 1.0,
    tacticalWeight: 1.0,
  },
  {
    id: 'aggressive',
    name: 'The Valkyrie',
    avatar: '⚔️',
    tagline: 'Ruthless kingside attacker',
    description: 'Sacrifices pawns for initiative, launches relentless kingside storms, and avoids quiet piece trades.',
    kingAttackWeight: 1.8,
    centerControlWeight: 0.9,
    tacticalWeight: 1.5,
  },
  {
    id: 'positional',
    name: 'The Architect',
    avatar: '🏰',
    tagline: 'Master of outposts and structure',
    description: 'Patient, squeezes subtle weaknesses, locks pawn structures, and maneuvers for overwhelming endgame superiority.',
    kingAttackWeight: 0.7,
    centerControlWeight: 1.6,
    tacticalWeight: 0.8,
  },
  {
    id: 'tactical',
    name: 'The Magician',
    avatar: '✨',
    tagline: 'Trickster and combinationalist',
    description: 'Loves sharp complications, pins, forks, and deflection tactics. Constant tactical alertness.',
    kingAttackWeight: 1.3,
    centerControlWeight: 1.0,
    tacticalWeight: 1.9,
  },
];

export const TIME_CONTROLS: TimeControlConfig[] = [
  { id: 'bullet_1_0', label: '1+0 Bullet', category: 'bullet', baseMinutes: 1, incrementSeconds: 0 },
  { id: 'blitz_3_2', label: '3+2 Blitz', category: 'blitz', baseMinutes: 3, incrementSeconds: 2 },
  { id: 'blitz_5_0', label: '5+0 Blitz', category: 'blitz', baseMinutes: 5, incrementSeconds: 0 },
  { id: 'rapid_10_5', label: '10+5 Rapid', category: 'rapid', baseMinutes: 10, incrementSeconds: 5 },
  { id: 'classical_30_0', label: '30+0 Classical', category: 'classical', baseMinutes: 30, incrementSeconds: 0 },
  { id: 'none', label: 'No Clock (Casual)', category: 'none', baseMinutes: 0, incrementSeconds: 0 },
];

export interface BotCharacter {
  level: number;
  name: string;
  title: string;
  elo: number;
  avatar: string;
  personality: AIPersonalityId;
  style: string;
  tier: 'beginner' | 'intermediate' | 'master';
  desc: string;
}

export const BOT_CHARACTERS: BotCharacter[] = [
  {
    level: 1,
    name: 'Jimmy',
    title: 'Novice Bot',
    elo: 600,
    avatar: '🤖',
    personality: 'balanced',
    style: 'Casual',
    tier: 'beginner',
    desc: 'Overlooks hanging pieces, perfect for beginners learning basics.',
  },
  {
    level: 2,
    name: 'Martin',
    title: 'Calm Novice',
    elo: 800,
    avatar: '🥋',
    personality: 'balanced',
    style: 'Beginner',
    tier: 'beginner',
    desc: 'Knows rules and simple checks, struggles with multi-step tactics.',
  },
  {
    level: 3,
    name: 'Elena',
    title: 'Sharp Casual',
    elo: 1000,
    avatar: '🎯',
    personality: 'tactical',
    style: 'Tactical',
    tier: 'beginner',
    desc: 'Likes early attacks and pins, occasional tactical slips in endgames.',
  },
  {
    level: 4,
    name: 'Nelson',
    title: 'Club Novice',
    elo: 1200,
    avatar: '⚔️',
    personality: 'aggressive',
    style: 'Aggressive',
    tier: 'intermediate',
    desc: 'Aggressive queen attacker. Punishes passive openings quickly.',
  },
  {
    level: 5,
    name: 'Antonio',
    title: 'Harmonic Intermediate',
    elo: 1400,
    avatar: '⚖️',
    personality: 'balanced',
    style: 'Balanced',
    tier: 'intermediate',
    desc: 'Solid central control, patient development, balanced play.',
  },
  {
    level: 6,
    name: 'Sofia',
    title: 'The Architect',
    elo: 1600,
    avatar: '🏰',
    personality: 'positional',
    style: 'Positional',
    tier: 'intermediate',
    desc: 'Locks pawn structures, targets outpost squares, strategic mastery.',
  },
  {
    level: 7,
    name: 'Laura',
    title: 'Tactical Magician',
    elo: 1800,
    avatar: '✨',
    personality: 'tactical',
    style: 'Tricky',
    tier: 'master',
    desc: 'Constantly sets tactical traps, forks, and deflection tactics.',
  },
  {
    level: 8,
    name: 'Viktor',
    title: 'Club Master',
    elo: 2000,
    avatar: '🦁',
    personality: 'aggressive',
    style: 'Grandmaster',
    tier: 'master',
    desc: 'Fierce calculation and strong endgame conversion.',
  },
  {
    level: 9,
    name: 'Alexander',
    title: 'International Master',
    elo: 2200,
    avatar: '🦅',
    personality: 'positional',
    style: 'Master',
    tier: 'master',
    desc: 'Deep positional pressure, tight endgame play, and strategic mastery.',
  },
  {
    level: 10,
    name: 'Magnus',
    title: 'World Champion',
    elo: 2500,
    avatar: '👑',
    personality: 'balanced',
    style: 'World Champion',
    tier: 'master',
    desc: 'World-champion deep iterative minimax search with quiescence horizon calculation.',
  },
];

export function getBotCharacter(level: number): BotCharacter {
  return BOT_CHARACTERS.find((b) => b.level === level) || BOT_CHARACTERS[3];
}

