import { DifficultyConfig, AIPersonality, TimeControlConfig } from '../types/chess';

export const DIFFICULTY_LEVELS: DifficultyConfig[] = [
  {
    level: 1,
    name: 'Novice (600 Elo)',
    elo: 600,
    depth: 1,
    skillLevel: 1,
    blunderProbability: 0.35,
    moveTimeMs: 150,
    description: 'Makes frequent casual mistakes, overlooks simple hanging pieces.',
    avatarBg: 'from-amber-600 to-amber-800',
  },
  {
    level: 2,
    name: 'Beginner (800 Elo)',
    elo: 800,
    depth: 2,
    skillLevel: 3,
    blunderProbability: 0.22,
    moveTimeMs: 200,
    description: 'Knows basic moves, but struggles with multi-move tactics and pins.',
    avatarBg: 'from-yellow-600 to-amber-700',
  },
  {
    level: 3,
    name: 'Casual (1000 Elo)',
    elo: 1000,
    depth: 2,
    skillLevel: 5,
    blunderProbability: 0.12,
    moveTimeMs: 250,
    description: 'Solid opening awareness, occasionally blunders tactics in complex positions.',
    avatarBg: 'from-emerald-600 to-green-800',
  },
  {
    level: 4,
    name: 'Club Novice (1200 Elo)',
    elo: 1200,
    depth: 3,
    skillLevel: 8,
    blunderProbability: 0.06,
    moveTimeMs: 300,
    description: 'Understands basic strategy, center control, and common tactical motifs.',
    avatarBg: 'from-teal-600 to-emerald-800',
  },
  {
    level: 5,
    name: 'Intermediate (1400 Elo)',
    elo: 1400,
    depth: 3,
    skillLevel: 11,
    blunderProbability: 0.02,
    moveTimeMs: 350,
    description: 'Rarely leaves pieces hanging. Formulates tactical attack plans.',
    avatarBg: 'from-cyan-600 to-blue-800',
  },
  {
    level: 6,
    name: 'Advanced (1600 Elo)',
    elo: 1600,
    depth: 3,
    skillLevel: 14,
    blunderProbability: 0.0,
    moveTimeMs: 400,
    description: 'Strong tactical vision, good pawn structure knowledge, active endgames.',
    avatarBg: 'from-blue-600 to-indigo-800',
  },
  {
    level: 7,
    name: 'Club Player (1800 Elo)',
    elo: 1800,
    depth: 4,
    skillLevel: 16,
    blunderProbability: 0.0,
    moveTimeMs: 450,
    description: 'Plays precise theoretical lines and punishes small positional errors.',
    avatarBg: 'from-indigo-600 to-purple-800',
  },
  {
    level: 8,
    name: 'Expert (2000 Elo)',
    elo: 2000,
    depth: 4,
    skillLevel: 18,
    blunderProbability: 0.0,
    moveTimeMs: 500,
    description: 'Formidable opponent with deep calculation and strong endgame technique.',
    avatarBg: 'from-purple-600 to-fuchsia-800',
  },
  {
    level: 9,
    name: 'Master (2200 Elo)',
    elo: 2200,
    depth: 4,
    skillLevel: 19,
    blunderProbability: 0.0,
    moveTimeMs: 600,
    description: 'Near-flawless tactical accuracy and strategic mastery.',
    avatarBg: 'from-rose-600 to-pink-900',
  },
  {
    level: 10,
    name: 'Grandmaster (2500 Elo)',
    elo: 2500,
    depth: 5,
    skillLevel: 20,
    blunderProbability: 0.0,
    moveTimeMs: 700,
    description: 'Master-level iterative deepening with quiescence tactical horizon search.',
    avatarBg: 'from-red-600 to-amber-900',
  },
];

export const AI_PERSONALITIES: AIPersonality[] = [
  {
    id: 'balanced',
    name: 'Harmonic Engine',
    avatar: '⚖️',
    tagline: 'Objective, calm, and balanced',
    description: 'Plays standard chess theory, balances tactical aggression with solid positional structure.',
    kingAttackWeight: 1.0,
    centerControlWeight: 1.0,
    tacticalWeight: 1.0,
  },
  {
    id: 'aggressive',
    name: 'The Valkyrie',
    avatar: '⚔️',
    tagline: 'Ruthless kingside attacker',
    description: 'Sacrifices pawns for initiative, launches relentless kingside storms, and avoids quiet piece trades.',
    kingAttackWeight: 1.8,
    centerControlWeight: 0.9,
    tacticalWeight: 1.5,
  },
  {
    id: 'positional',
    name: 'The Architect',
    avatar: '🏰',
    tagline: 'Master of outposts and structure',
    description: 'Patient, squeezes subtle weaknesses, locks pawn structures, and maneuvers for overwhelming endgame superiority.',
    kingAttackWeight: 0.7,
    centerControlWeight: 1.6,
    tacticalWeight: 0.8,
  },
  {
    id: 'tactical',
    name: 'The Magician',
    avatar: '✨',
    tagline: 'Trickster and combinationalist',
    description: 'Loves sharp complications, pins, forks, and deflection tactics. Constant tactical alertness.',
    kingAttackWeight: 1.3,
    centerControlWeight: 1.0,
    tacticalWeight: 1.9,
  },
];

export const TIME_CONTROLS: TimeControlConfig[] = [
  { id: 'bullet_1_0', label: '1+0 Bullet', category: 'bullet', baseMinutes: 1, incrementSeconds: 0 },
  { id: 'blitz_3_2', label: '3+2 Blitz', category: 'blitz', baseMinutes: 3, incrementSeconds: 2 },
  { id: 'blitz_5_0', label: '5+0 Blitz', category: 'blitz', baseMinutes: 5, incrementSeconds: 0 },
  { id: 'rapid_10_5', label: '10+5 Rapid', category: 'rapid', baseMinutes: 10, incrementSeconds: 5 },
  { id: 'classical_30_0', label: '30+0 Classical', category: 'classical', baseMinutes: 30, incrementSeconds: 0 },
  { id: 'none', label: 'No Clock (Casual)', category: 'none', baseMinutes: 0, incrementSeconds: 0 },
];
